---
- name: Config | Render Configuration
  template:
    src: config.j2
    dest: "{{ observium.install_dir }}/config.php"
  notify: reload apache

- name: Config | Render SNMP Client/MIB
  template:
    src: snmp.j2
    dest: /etc/snmp/snmp.conf

- name: Config | Migrate Database
  command: "php {{ observium.install_dir }}/build-base.php chdir={{ observium.install_dir }}"
  when: perms.changed

- name: Config | LibreNMS VirtualHost
  template:
    src: vhost.j2
    dest: /etc/apache2/sites-available/librenms.conf
  notify: reload apache

- name: Config | VirtualHost Symlink
  file:
    src: /etc/apache2/sites-available/librenms.conf
    dest: /etc/apache2/sites-enabled/librenms.conf
    state: link
  notify: reload apache

- name: Config | Default VirtualHost
  file:
    src: /etc/apache2/sites-available/000-default.conf
    dest: /etc/apache2/sites-enabled/000-default.conf
    state: link
  notify: reload apache

- name: Config | Enable mod_rewrite
  apache2_module:
    state: present
    name: rewrite
  notify: reload apache

- name: Config | Enable php5 Apache Module
  apache2_module:
    name: php5
  notify: reload apache
