---
- include: install.yml
  tags: [ 'install' ]

- include: config.yml
  tags: [ 'config' ]

- include: weathermap.yml
  tags: [ 'weathermap' ]

- name: Main | Start Apache
  service:
    name: apache2
    state: started
    enabled: true
