---
- name: Package Installation
  apt:
    name={{ item }}
    cache_valid_time={{ apt.cachetime }}
    update_cache=yes
  with_items:
    [ 'apache2', 'libapache2-mod-php5', 'php5-cli', 'php5-mysql',
      'php5-gd', 'php5-snmp', 'php-pear', 'php-net-ipv4', 'php-net-ipv6',
      'snmp', 'graphviz', 'php5-mcrypt', 'mysql-client', 'rrdtool',
      'fping', 'imagemagick', 'whois', 'mtr-tiny', 'nmap',
      'ipmitool', 'python-mysqldb' ]
  tags: [ 'packages' ]

- name: LibreNMS Git Checkout
  git:
    repo=https://github.com/librenms/librenms
    depth=1
    dest={{ observium.install_dir }}
  register: perms

- name: Upload Branding
  copy:
    src=files/images/{{ observium.title_image }}
    dest={{ observium.install_dir }}/html/images
    owner={{ observium.user }}
    group={{ observium.user }}

- name: Create Directories
  file:
    path={{ observium.install_dir }}/{{ item }}
    state=directory
    owner={{ observium.user }}
    group={{ observium.user }}
  with_items:
    - rrd
    - logs

- name: Render Configuration
  template:
    src=config.j2
    dest={{ observium.install_dir }}/config.php
  notify: reload apache

- name: Render SNMP Client/MIB Configuration
  template:
    src=snmp.j2
    dest=/etc/snmp/snmp.conf

- name: Migrate Database
  command: php {{ observium.install_dir }}/build-base.php chdir={{ observium.install_dir }}
  when: perms.changed

- name: Apache VirtualHost
  template:
    src=vhost.j2
    dest=/etc/apache2/sites-available/librenms.conf
  notify: reload apache

- name: VirtualHost Symlink
  file:
    src=/etc/apache2/sites-available/librenms.conf
    dest=/etc/apache2/sites-enabled/librenms.conf
    state=link
  notify: reload apache

- name: Default VirtualHost
  file:
    src=/etc/apache2/sites-available/000-default.conf
    dest=/etc/apache2/sites-enabled/000-default.conf
    state=link
  notify: reload apache

- name: enable mod_rewrite
  apache2_module:
    state=present
    name=rewrite
  notify: reload apache

- name: Apache Service
  service:
    name=apache2
    state=started
    enabled=true

- name: Observium Cron Job
  template:
    src=cron.j2
    dest=/etc/cron.d/librenms
