---
- name: Weathermap Git Checkout
  git:
    repo=https://github.com/laf/weathermap
    depth=1 update=yes
    dest={{ observium.install_dir }}/html/weathermap
  register: git

- name: Weathermap Permissions
  file:
    path={{ observium.install_dir }}/html/weathermap
    owner={{ observium.user }}
    group={{ observium.user }}
    state=directory
    recurse=true
  when: git.changed

- name: Maps Directory
  file:
    path={{ observium.install_dir }}/html/weathermap/maps
    owner={{ observium.user }}
    group={{ observium.user }}
    state=directory
  when: git.changed

- name: LibreNMS Menubar
  template:
    src=weather_menubar.j2
    dest={{ observium.install_dir }}/html/includes/print-menubar-custom.inc.php
