---
- name: Weathermap | Git Checkout
  git:
    repo: https://github.com/librenms-plugins/Weathermap
    dest: "{{ observium.install_dir }}/html/plugins/Weathermap"
  become_user: "{{ observium.user }}"
  ignore_errors: true

- name: Weathermap | Maps Directory
  file:
    path: "{{ observium.install_dir }}/html/plugins/Weathermap/maps"
    state: directory
    owner: "{{ observium.user }}"
    group: "{{ observium.user }}"
