---
- name: Install | Management Packages
  apt:
    name: "{{ item }}"
  with_items:
    [ 'iptables', 'iptables-persistent', 'conntrack',
      'conntrackd', 'netstat-nat', 'iptstate', 'ipset' ]
  tags: [ 'packages' ]

- name: Install | Runtime Disable RP Filter
  sysctl:
    name: net.ipv4.conf.all.rp_filter
    value: 0
    sysctl_set: yes
    reload: yes

- name: Install | Runtime Log Martians
  sysctl:
    name: net.ipv4.conf.all.log_martians
    value: 1
    sysctl_set: yes
    reload: yes

- name: Install | Ignore DHCP nameservers
  template:
    src: dhclient.j2
    dest: /etc/dhcp/dhclient.conf
  notify: warn dhclient
