---
- name: IPSet | Render IPSet Config
  template:
    src: ipset.j2
    dest: /etc/ipset.conf
  notify: restore ipset

# Remove legacy init script
- name: IPSet | Remove custom netfilter-sysctl
  file:
    path: /etc/init.d/ipset
    state: absent

- name: IPSet | Install systemd unit
  template:
    src: units/ipset-unit.j2
    dest: /etc/systemd/system/ipset.service
  notify: reload daemons

- name: IPSet | Start Service
  service:
    name: ipset
    state: started
    enabled: true

- meta: flush_handlers
