---
- name: IPSet | Render IPSet Config
  template:
    src: ipset.j2
    dest: /etc/ipset.conf
  notify: restore ipset

- name: Install | Remove custom netfilter-sysctl
  file:
    path: /etc/init.d/ipset
    state: absent

- name: IPSet | Install systemd unit
  template:
    src: ipset-unit.j2
    dest: /etc/systemd/system/ipset.service
  notify: reload daemons

- name: IPSet | Start Service
  service:
    name: ipset
    state: started
    enabled: true
