---
- name: IPTables | Render Rules
  template:
    src: iptables.j2
    dest: "{{ iptables_path | default('/etc/iptables/rules.v4') }}"
  notify: restore iptables
  tags: [ 'iptables' ]

- name: IPTables | Remove custom netfilter-sysctl
  file:
    path: /etc/init.d/netfilter-sysctl
    state: absent

- name: IPTables | Custom netfilter-sysctl service
  service:
    name: netfilter-sysctl
    state: stopped
    enabled: false

- name: IPTables | Netfilter unit w/ sysctl reload
  template:
    src: units/sysctl-unit.j2
    dest: /etc/systemd/system/netfilter-persistent.service
  notify: reload daemons

- name: IPTables | Custom netfilter-sysctl service
  service:
    name: netfilter-persistent
    state: started
    enabled: true
  tags: [ 'services' ]
