---
- name: Install | Check for SSH keys
  assert:
    that:
      - "'{{ lookup('file', 'files/keys/bgpanel/bgpanel.key') }}' is string"
      - "'{{ lookup('file', 'files/keys/bgpanel/bgpanel.pub') }}' is string"
    msg: Generate an SSH keypair under files/bgpanel/bgpanel.key and .pub

- name: Install | Default API Key
  assert:
    that:
      - "bgp_apikey != 'apikey'"
    msg: Specify a valid bgp_apikey


- name: Install | PHP5
  apt:
    name: "{{ item }}"
    force: true
  with_items:
    - php5
    - php5-curl

- name: Install | Game User
  user:
    name: game
    createhome: yes

- name: Install | BGPanel Pubkey
  authorized_key:
    user: game
    manage_dir: yes
    key: "{{ lookup('file', 'files/keys/bgpanel/bgpanel.pub') }}"

- name: Install | BGPanel Announce Directory
  file:
    path: "{{ bgp_announce_install_dir }}"
    state: directory

- name: Install | BGPanel Announcer from Git
  git:
    repo: "{{ bgp_announce_git }}"
    dest: "{{ bgp_announce_install_dir }}"
    update: yes

- name: Install | Render Configuration
  template:
    src: bgp-announce.cfg.j2
    dest: "{{ bgp_announce_install_dir }}/config.php.inc"

- name: Install | Systemd Unit
  template:
    src: bgp-announce.unit.j2
    dest: /lib/systemd/system/bgp-announce.service
  notify:
    - reload daemons

- name: Install | BGPanel Announcer
  service:
    name: bgp-announce
    state: started
    enabled: true
