---
- include: csgo/warmod.yml
  when: csgo_warmod | default(false)
  tags: warmod

- include: csgo/csay.yml
  tags: csay

- name: CSGO | Install Server Configs
  template:
    src: csgo/server.j2
    dest: "{{ steamcmd_path }}/games/csgo/csgo/cfg/server_{{ item.key }}.cfg"
    owner: "{{ steamcmd_user }}"
    group: "{{ steamcmd_user }}"
  with_dict: "{{ csgo_server_instances }}"
  tags: [ 'configs' ]

- name: CSGO | Install esl5on5
  template:
    src: csgo/esl5on5.j2
    dest: "{{ steamcmd_path }}/games/csgo/csgo/cfg/rules_esl5on5.cfg"
    owner: "{{ steamcmd_user }}"
    group: "{{ steamcmd_user }}"

# This is to prevent WarMod from installing its own gamemode_competitive_server.cfg
# including lower tickrates, which is very bad practice.
# esl5on5 symlink is provided for convenience.
- name: CSGO | esl5on5 aliases
  file:
    state: link
    force: yes
    src: "{{ steamcmd_path }}/games/csgo/csgo/cfg/rules_esl5on5.cfg"
    dest: "{{ steamcmd_path }}/games/csgo/csgo/cfg/{{ item }}.cfg"
    owner: "{{ steamcmd_user }}"
    group: "{{ steamcmd_user }}"
  with_items:
    - esl5on5
    - gamemode_competitive_server

- name: CSGO | Environment Vars Directory
  file:
    state: directory
    path: "{{ steamcmd_path }}/games/csgo/env"
    owner: "{{ steamcmd_user }}"
    group: "{{ steamcmd_user }}"

- name: CSGO | Server Environment Vars
  template:
    src: csgo/systemd-env.j2
    dest: "{{ steamcmd_path }}/games/csgo/env/env_{{ item.key }}"
    owner: "{{ steamcmd_user }}"
    group: "{{ steamcmd_user }}"
  with_dict: "{{ csgo_server_instances }}"
  tags: [ 'config' ]

- name: CSGO | systemd unit
  template:
    src: csgo/systemd-unit.j2
    dest: /lib/systemd/system/csgo@.service
  tags: [ 'systemd' ]

- name: CSGO | Enable and Start
  service:
    name: "csgo@{{ item.key }}"
    enabled: true
    state: started
  with_dict: "{{ csgo_server_instances }}"
