---
- include: install.yml

- include: steamcmd.yml
  when: steamcmd_run == 'YES'

- include: csgo.yml
  when: steam_games.csgo is defined
  tags: [ 'csgo' ]

- include: qlive.yml
  when: steam_games.ql is defined
  tags: [ 'qlive' ]
