---
- include: install.yml
- include: steamcmd.yml

- include: csgo.yml
  when: steam_games.csgo is defined
  tags: [ 'csgo' ]

- include: qlive.yml
  when: steam_games.ql is defined
  tags: [ 'qlive' ]
