---
- name: SteamCMD | First Run
  command: ./steamcmd.sh +quit
  args:
    chdir: "{{ steamcmd_path }}"
  become_user: "{{ steamcmd_user }}"
  when: steamrc.changed

- name: SteamCMD | Update and Validate Games
  command: "./steamcmd.sh +login {{ steam_account | default('anonymous') }} {{ steam_password | default('') }} \
              +force_install_dir ./games/{{ item.key }} +app_update {{ item.value.id }} {{ (steamcmd_update | default(false) == 'YES') | ternary('validate', '') }} +quit"
  args:
    chdir: "{{ steamcmd_path }}"
  become_user: "{{ steamcmd_user }}"
  with_dict: "{{ steam_games }}"
  tags: [ 'update', 'steamcmd' ]
