---
- name: SteamCMD | First Run
  command: ./steamcmd.sh +quit
  args:
    chdir: "{{ steamcmd_path }}"
  become_user: "{{ steamcmd_user }}"
  when: steamrc.changed

- name: SteamCMD | Install Games
  command: "./steamcmd.sh +login {{ steam_account }} +force_install_dir ./games/{{ item.key }} +app_update {{ item.value.id }} +quit"
  args:
    chdir: "{{ steamcmd_path }}"
  become_user: "{{ steamcmd_user }}"
  with_dict: steam_games
  tags: [ 'install', 'steamcmd' ]

- name: SteamCMD | Update Games
  command: "./steamcmd.sh +login {{ steam_account }} +force_install_dir ./games/{{ item.key }} +app_update {{ item.value.id }} validate +quit"
  args:
    chdir: "{{ steamcmd_path }}"
  become_user: "{{ steamcmd_user }}"
  with_dict: steam_games
  when: steam_update | default(false)
  tags: [ 'update', 'steamcmd' ]
