---
- name: Warmod | Create Addons Directory
  file:
    path: "{{ steamcmd_path }}/games/csgo/csgo/addons"
    state: directory
  become_user: "{{ steamcmd_user }}"

- name: Warmod | Download MM:Source
  get_url:
    dest: "{{ steamcmd_path }}/games/csgo/csgo/addons/mmsource-linux.tar.gz"
    url: "{{ csgo_mm_url }}"
  become_user: "{{ steamcmd_user }}"

- name: Warmod | Unpack MM:Source
  unarchive:
    copy: no
    src: "{{ steamcmd_path }}/games/csgo/csgo/addons/mmsource-linux.tar.gz"
    dest: "{{ steamcmd_path }}/games/csgo/csgo"
    creates: "{{ steamcmd_path}}/games/csgo/csgo/addons/metamod"
  become_user: "{{ steamcmd_user }}"

- name: Warmod | Download SourceMod
  get_url:
    dest: "{{ steamcmd_path }}/games/csgo/csgo/addons/sourcemod-linux.tar.gz"
    url: "{{ csgo_sm_url }}"
  become_user: "{{ steamcmd_user }}"

- name: Warmod | Unpack SourceMod
  unarchive:
    copy: no
    src: "{{ steamcmd_path }}/games/csgo/csgo/addons/sourcemod-linux.tar.gz"
    dest: "{{ steamcmd_path }}/games/csgo/csgo"
    creates: "{{ steamcmd_path}}/games/csgo/csgo/addons/sourcemod"
  become_user: "{{ steamcmd_user }}"

- name: Warmod | Download WarMod
  get_url:
    dest: "{{ steamcmd_path }}/games/csgo/csgo/addons/sourcemod/plugins/warmod.smx"
    url: "{{ csgo_wm_url }}"
  become_user: "{{ steamcmd_user }}"

- name: Warmod | SourceMod Admin Overrides
  template:
    src: "csgo/sourcemod/admin_overrides.j2"
    dest: "{{ steamcmd_path }}/games/csgo/csgo/addons/sourcemod/configs/admin_overrides.cfg"
  become_user: "{{ steamcmd_user }}"

- name: Warmod | SourceMod Admin Menu
  template:
    src: "csgo/sourcemod/adminmenu_custom.j2"
    dest: "{{ steamcmd_path }}/games/csgo/csgo/addons/sourcemod/configs/adminmenu_custom.txt"
  become_user: "{{ steamcmd_user }}"
