---
- name: lxc | Install LXC packages
  apt:
    name: "{{ item }}"
    update_cache: yes
    cache_valid_time: "{{ apt_cache_valid | default('86400') }}"
    default_release: "{{ lxc_release | default('jessie-backports') }}"
  with_items:
    - lxc
    - lxc-dev
  tags: [ 'packages' ]

- name: Install | Install OVS scripts
  template:
    src: "{{ item }}.j2"
    dest: "/etc/lxc/{{ item }}"
    mode: 0755
  with_items:
    - ovs-up
    - ovs-down

# Required for building lxc-python2 for Ansible
- name: lxc | Install pip and python-dev for Ansible module
  apt:
    name: "{{ item }}"
    update_cache: yes
    cache_valid_time: "{{ apt_cache_valid | default('86400') }}"
  with_items:
    - python-pip
    - python-dev
  tags: [ 'packages' ]

- name: lxc | Python Bindings
  pip:
    executable: pip2
    name: lxc-python2

- name: lxc | Enable LXC Autostart
  service:
    name: lxc
    enabled: true
