---
- name: lxc | Install LXC packages
  apt:
    name: "{{ item }}"
    update_cache: yes
    cache_valid_time: "{{ apt_cache_valid | default('86400') }}"
    default_release: "{{ lxc_release | default('jessie-backports') }}"
  with_items:
    - lxc
    - lxc-dev
  tags: [ 'packages' ]

# We need the ip_tables kernel module family loaded
# so LXC containers can use them.
- name: lxc | Install iptables-persistent
  apt:
    name: iptables-persistent

- name: lxc | Conntrack kernel module configuration
  lineinfile:
    dest: /etc/modprobe.d/lanparty.conf
    line: "options nf_conntrack hashsize={{ gw_config.conntrack_max }}"
    create: yes
  when: gw_config is defined and gw_config.conntrack_max is defined

- name: lxc | Run netfilter-persistent for kernel modules
  service:
    name: netfilter-persistent
    state: started
    enabled: true

- name: lxc | Set conntrack kernel parameters for lp-gw
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    sysctl_set: yes
    reload: yes
  tags: [ 'kernel' ]
  with_items:
    - { name: 'net.netfilter.nf_conntrack_max', value: "{{ gw_config.conntrack_max | default(300000) }}" }
    - { name: 'net.netfilter.nf_conntrack_buckets', value: "{{ gw_config.conntrack_max | default(300032) }}" }

- name: lxc | Install OVS scripts
  template:
    src: "{{ item }}.j2"
    dest: "/etc/lxc/{{ item }}"
    mode: 0755
  with_items:
    - ovs-up
    - ovs-down

# Required for building lxc-python2 for Ansible
- name: lxc | Install pip and python-dev for Ansible module
  apt:
    name: "{{ item }}"
    update_cache: yes
    cache_valid_time: "{{ apt_cache_valid | default('86400') }}"
  with_items:
    - python-pip
    - python-dev
  tags: [ 'packages' ]

- name: lxc | Python Bindings
  pip:
    executable: pip2
    name: lxc-python2

- name: lxc | Enable LXC Autostart
  service:
    name: lxc
    enabled: true
