---
- name: Manage | Clean up stale LXC subsystem lock
  file:
    path: /var/lock/subsys/lxc
    state: absent

- name: Manage | Find existing containers
  stat:
    path: "/var/lib/lxc/{{ item.key }}"
  with_dict: "{{ lxc_containers }}"
  register: lxcdirs

- name: Manage | Create Containers
  lxc_container:
    name: "{{ item.item.key }}"
    template: download
    template_options: >
      --dist {{ item.item.value.distro | default('debian') }}
      --release {{ item.item.value.release | default('jessie') }}
      --arch {{ item.item.value.arch | default('amd64') }}
    backing_store: "{{ item.item.value.store | default('dir') }}"
    vg_name: "{{ lxc_vg | default('lxc') }}"
    state: stopped
  when: not item.stat.exists
  with_items: "{{ lxcdirs.results }}"
  register: lxccreate

- name: Manage | Container Mounts
  template:
    src: fstab.j2
    dest: "/var/lib/lxc/{{ item.key }}/fstab"
  with_dict: "{{ lxc_containers }}"

- name: Manage | Container Configurations
  template:
    src: lxc-config.j2
    dest: "/var/lib/lxc/{{ item.key }}/config"
  register: lxcconfig
  with_dict: "{{ lxc_containers }}"

- name: Manage | Debian | Render Network Configuration
  template:
    src: lxc-eni.j2
    dest: "/var/lib/lxc/{{ item.key }}/rootfs/etc/network/interfaces"
  with_dict: "{{ lxc_containers }}"
  when: item.value.store | default('dir') == 'dir' and
        item.value.distro | default('debian') == 'debian'

# lxc restart behaviour is split into start/stop
# possible bug or race condition in tooling or Ansible module
- name: Manage | Stop Modified Containers when lxc_restart == YES
  lxc_container:
    name: "{{ item.item.key }}"
    state: restarted
  when: item.changed and lxc_restart == 'YES'
  with_items: "{{ lxcconfig.results }}"

- name: Manage | Start All Defined Containers
  lxc_container:
    name: "{{ item.key }}"
    state: started
  with_dict: "{{ lxc_containers }}"

- name: Manage | Install Basic Packages
  lxc_container:
    name: "{{ item.lxc_container.name }}"
    container_command: |
      DEBIAN_FRONTEND=noninteractive \
      apt-get -y install \
        sudo \
        python \
        openssh-server \
        ca-certificates
  with_items: "{{ lxccreate.results }}"
  when: item.lxc_container is defined
