---
- name: lxc | Clean up stale LXC subsystem lock
  file:
    path: /var/lock/subsys/lxc
    state: absent

- name: lxc | Find existing containers
  stat:
    path: "/var/lib/lxc/{{ item.key }}"
  with_dict: "{{ lxc_containers }}"
  register: lxcdirs

- name: lxc | Create Containers
  lxc_container:
    name: "{{ item.item.key }}"
    template: download
    template_options: >
      --dist {{ item.item.value.distro | default('debian') }}
      --release {{ item.item.value.release | default('jessie') }}
      --arch {{ item.item.value.arch | default('amd64') }}
    container_command: "apt-get install sudo python inetutils-ping openssh-server"
    backing_store: "{{ item.item.value.store | default('dir') }}"
    vg_name: "{{ lxc_vg | default('lxc') }}"
    state: stopped
  when: not item.stat.exists
  with_items: "{{ lxcdirs.results }}"

- name: lxc | Render Configurations
  template:
    src: lxc-config.j2
    dest: "/var/lib/lxc/{{ item.key }}/config"
  register: lxcconfig
  with_dict: "{{ lxc_containers }}"

- name: lxc | Debian | Render Network Configuration
  template:
    src: lxc-eni.j2
    dest: "/var/lib/lxc/{{ item.key }}/rootfs/etc/network/interfaces"
  with_dict: "{{ lxc_containers }}"
  when: item.value.store | default('dir') == 'dir' and
        item.value.distro | default('debian') == 'debian'

# lxc restart behaviour is split into start/stop
# possible bug or race condition in tooling or Ansible module
- name: lxc | Stop Modified Containers when lxc_restart == YES
  lxc_container:
    name: "{{ item.item.key }}"
    state: restarted
  when: item.changed and lxc_restart == 'YES'
  with_items: "{{ lxcconfig.results }}"

- name: lxc | Start All Defined Containers
  lxc_container:
    name: "{{ item.key }}"
    state: started
  with_dict: "{{ lxc_containers }}"

- name: lxc | Root .ssh directory
  file:
    path: "/var/lib/lxc/{{ item.key }}/rootfs/root/.ssh"
    state: directory
    mode: 0700
  with_dict: "{{ lxc_containers }}"
  when: item.value.store | default('dir') == 'dir'

- name: lxc | Root authorized_keys
  template:
    src: ssh-keys.j2
    dest: "/var/lib/lxc/{{ item.key }}/rootfs/root/.ssh/authorized_keys"
    mode: 0600
  with_dict: "{{ lxc_containers }}"
  when: item.value.store | default('dir') == 'dir'
