---
- include: install.yml
  tags: [ 'install' ]

- include: configure.yml
  tags: [ 'configure' ]

- include: run.yml
  tags: [ 'run' ]

- include: consul.yml
  tags: [ 'consul' ]
  when: consul_agent_enable | default(false) == true
