---
- name: Nginx | Stop and disable Apache
  service:
    name: apache2
    state: stopped
    enabled: false

- name: Nginx | Install Nginx
  apt:
    name: nginx
  tags: [ 'packages' ]

- name: Nginx | Render Configuration
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify: restart nginx

- name: Nginx | Disable Default Site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: reload nginx
  when: nginx_disable_default

- name: Nginx | Start Service
  service:
    name: nginx
    state: started
    enabled: true
