---
- name: Install | Packages
  apt:
    name: "{{ item }}"
  with_items:
    - netcat
    - bzip2
  tags: [ 'packages' ]

- name: Install | Old compat (Lenny) MySQL Library
  apt:
    deb: http://archive.debian.org/debian/pool/main/m/mysql-dfsg-5.0/libmysqlclient15off_5.0.32-7etch12_amd64.deb
  when: ts.mysql_compat | default(false)

- name: Install | TeamSpeak3 User
  user:
    name: "{{ ts.user }}"
    createhome: no
    system: yes

- name: Install | Create Installation Directory
  file:
    path: "{{ ts.install_dir }}/tarballs"
    state: directory
    owner: "{{ ts.user }}"
    group: "{{ ts.user }}"

- name: Install | Fetch Tarball
  get_url:
    url: "{{ ts.url }}"
    dest: "{{ ts.install_dir }}/tarballs/"
  register: tarball
  tags: tarball

- name: Install | Unpack Tarball
  unarchive:
    copy: no
    src: "{{ ts.install_dir }}/tarballs/{{ ts.url | basename }}"
    dest: "{{ ts.install_dir }}"
    owner: "{{ ts.user }}"
    group: "{{ ts.user }}"
  when: tarball.changed
  notify: restart ts3
  tags: tarball

- name: Install | Check Leading Directory
  stat:
    path: "{{ ts.install_dir }}/{{ ts.leading_dir }}"
  register: p

- name: Install | Install TeamSpeak3 Files
  shell: "rsync -a {{ ts.install_dir }}/{{ ts.leading_dir }}/ {{ ts.install_dir }}/"
  when: p.stat.isdir is defined and p.stat.isdir

- name: Install | Remove Leading Directory
  file:
    path: "{{ ts.install_dir }}/{{ ts.leading_dir }}"
    state: absent
