---
- name: TS3 | TeamSpeak3 Configuration
  template:
    src: ts3server.ini.j2
    dest: "{{ ts.install_dir }}/ts3server.ini"

- name: TS3 | MySQL Client Configuration
  template:
    src: ts3db.ini.j2
    dest: "{{ ts.install_dir }}/ts3db_{{ ts.db_driver }}.ini"

- name: TS3 | File Permissions
  file:
    path: "{{ ts.install_dir }}"
    owner: "{{ ts.user }}"
    group: "{{ ts.user }}"
    recurse: yes

- name: TS3 | Remove legacy init.d script
  file:
    path: /etc/init.d/teamspeak3
    state: absent

- name: TS3 | TS3 systemd Unit
  template:
    src: ts3unit.j2
    dest: /etc/systemd/system/teamspeak3.service
    mode: 755
  tags: [ 'services', 'units' ]

- name: TS3 | TeamSpeak3 Service
  service:
    name: teamspeak3
    state: started
    enabled: true
  tags: [ 'services' ]
