---
- include: verify.yml
  tags: [ 'verify' ]

- include: configure.yml
  tags: [ 'configure' ]

- include: run.yml
  tags: [ 'run' ]

- include: consul.yml
  when: consul_agent_enable | default(false) == true
  tags: [ 'consul' ]
