---
- name: Depot | Enable Sites
  file:
    state: link
    src: "/etc/nginx/sites-available/depot-{{ item.key }}"
    dest: "/etc/nginx/sites-enabled/depot-{{ item.key }}"
  with_dict: "{{ depot_sites }}"
  notify: reload nginx
