---
- name: Main | Kibana User
  user:
    name: "{{ kibana_user }}"
    home: "{{ kibana_install_dir }}"
    system: true

- name: Main | Ensure Directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ kibana_user }}"
    group: "{{ kibana_user }}"
  with_items:
    - "{{ kibana_install_dir }}"

- name: Main | Kibana Archive
  get_url:
    url: "{{ kibana_url }}"
    dest: "{{ kibana_install_dir }}/kibana-{{ kibana_version }}.tar.gz"
  register: dl

- name: Main | Extract Kibana
  unarchive:
    src: "{{ kibana_install_dir }}/kibana-{{ kibana_version }}.tar.gz"
    dest: "{{ kibana_install_dir }}"
    copy: no
  when: dl.changed
  become_user: "{{ kibana_user }}"

- name: Main | Unit File
  template:
    src: kibana.unit.j2
    dest: /lib/systemd/system/kibana.service
  notify: reload daemons

- meta: flush_handlers

- name: Main | Nginx Site
  template:
    src: nginx.site.j2
    dest: /etc/nginx/sites-available/kibana
  notify: reload nginx

- name: Main | Enable Nginx Site
  file:
    state: link
    src: /etc/nginx/sites-available/kibana
    dest: /etc/nginx/sites-enabled/kibana
  notify: restart nginx

- name: Main | Render Configuration
  template:
    src: kibana.conf.j2
    dest: "{{ kibana_install_dir }}/kibana-{{ kibana_version }}-linux-x64/config/kibana.yml"
  notify: restart kibana

- name: Main | Ensure Service
  service:
    name: kibana
    state: started
    enabled: true
