---
- name: BIND-DHCP | Config directory
  file:
    state: directory
    path: "{{ ns.dhcp.confdir }}"

- name: BIND-DHCP | Zone Configuration
  template:
    src: conf/dhcp.conf.j2
    dest: "{{ ns.dhcp.confdir }}/dhcp.conf"
  notify: reload bind

- name: BIND-DHCP | Zone Files
  template:
    force: no # Don't overwrite zone file!
    src: zones/domains.zone.j2
    dest: "{{ ns.dhcp.confdir }}/{{ item }}.db"
    owner: bind
    group: bind
  notify: reload bind
  with_items:
    - "{{ ns.dhcp.zone }}"
    - "rev.{{ ns.dhcp.zone }}"
  tags: [ 'zones' ]
