---
- name: Logging | Log Directory
  file:
    state: directory
    path: "{{ bind_logdir }}"
    owner: bind
    group: bind

- name: Logging | Install Logrotate
  template:
    src: logrotate.j2
    dest: /etc/logrotate.d/bind

- name: Logging | collectd config
  template:
    src: collectd.j2
    dest: /etc/collectd.d/bind.conf
  notify: restart collectd
