---
- name: BIND Name Server
  apt:
    name: bind9
  tags: [ 'packages' ]

- name: BIND RNDC Key
  template:
    src: rndc.key.j2
    dest: /etc/bind/rndc.key
  notify: restart bind

- name: BIND RNDC Key Configuration
  template:
    src: rndc.j2
    dest: /etc/bind/rndc.conf
  notify: reload bind

- name: BIND9 Configuration Files
  template:
    src: "{{ item }}.j2"
    dest: "/etc/bind/{{ item }}"
  notify: reload bind
  with_items:
    - named.conf
    - named.conf.options
    - named.conf.zones

- include: zones.yml
  tags: [ 'zones' ]

- include: dhcp.yml
  tags: [ 'dhcp' ]

- include: spoof.yml
  tags: [ 'spoof' ]

# Make sure we clean this up to avoid confusion
# and/or accidental manual edits to files that
# aren't being included by named.conf
- name: Clean up local BIND9 Configuration
  file:
    state: absent
    path: "/etc/bind/named.conf.{{ item }}"
  with_items:
    - local
    - default-zones

- name: BIND9 Service
  service:
    name: bind9
    state: started
    enabled: true
  tags: [ 'services' ]
