---
- name: Zones | Config directory
  file:
    state: directory
    path: "{{ ns.domains.confdir }}"

- name: Zones | Zone Files
  template:
    src: zones/domains.zone.j2
    dest: "{{ ns.domains.confdir }}/{{ item.name }}.db"
  with_items: "{{ ns.domains.zones }}"
  notify: reload bind
  tags: [ 'zones' ]

- name: Zones | Root Hints
  template:
    src: zones/root.hints.j2
    dest: /etc/bind/db.root
  notify: reload bind

- name: Zones | Config Files
  template:
    src: conf/domains.conf.j2
    dest: "{{ ns.domains.confdir }}/domains.conf"
  notify: reload bind
