---
- name: OVS | Config Sanity Check
  assert:
    that:
      - "openvswitch is defined"
      - "openvswitch is iterable"
      - "openvswitch is not string"
    msg: The 'openvswitch' variable must be defined

- name: OVS | Port Definition Check
  assert:
    that:
      - "item.ports is defined"
      - "item.ports is iterable"
      - "item.ports is not string"
    msg: openvswitch.<item>.ports cannot be missing, empty or string
  with_items: "{{ openvswitch }}"

- include: install.yml
  tags: [ 'install' ]

- include: manage.yml
  tags: [ 'manage' ]
