---
- name: Manage | Create Bridges
  openvswitch_bridge:
    bridge: "{{ item.name }}"
  with_items: "{{ openvswitch }}"

# Broken due to https://github.com/ansible/ansible-modules-extras/issues/2500
# - name: Manage | Create Ports
#   openvswitch_port:
#     bridge: "{{ item.name }}"
#     port: "{{ item.ports }}"
#   with_items: "{{ openvswitch }}"
