---
- name: Monitoring Agent | Install xinetd and Net-SNMP
  apt:
    name: "{{ item }}"
  with_items:
    - xinetd
    - snmpd
  tags: [ 'packages' ]

- name: Monitoring Agent | Check_MK Agent
  template:
    src: agent/check_mk_agent.j2
    dest: /usr/bin/check_mk_agent
    mode: u+x

- name: Monitoring Agent | Check_MK xinetd
  template:
    src: agent/check_mk_xinetd.j2
    dest: /etc/xinetd.d/check_mk
  notify: restart xinetd

# This calls to add the host to Observium
# Changes to this resource marks a new installation
- name: Monitoring Agent | Create Directories
  file:
    recurse: true
    path: "{{ item }}"
    state: directory
  with_items:
    - /usr/lib/check_mk_agent/plugins
    - /usr/lib/check_mk_agent/local
  register: addhost

- name: Monitoring Agent | Agent Plugins
  template:
    src: "agent/{{ item }}.j2"
    dest: "/usr/lib/check_mk_agent/local/{{ item }}"
  with_items:
    - apache

- name: Monitoring Agent | SNMPd Default Options
  lineinfile:
    dest: /etc/default/snmpd
    line: "SNMPDOPTS='-LS0-5d -Lf /dev/null -u snmp -p /var/run/snmpd.pid'"
    regexp: "^\\#?\\s?SNMPDOPTS"
  notify: restart snmpd

- name: Monitoring Agent | Distro Script
  template:
    src: agent/distro.j2
    dest: /usr/bin/distro
    mode: a+x

- name: Monitoring Agent | SNMPd Configuration
  template:
    src: agent/snmpd.j2
    dest: /etc/snmp/snmpd.conf
  notify: restart snmpd

- name: Monitoring Agent | SNMPd Service
  service:
    name: snmpd
    state: started
    enabled: true
  ignore_errors: true

- name: Monitoring Agent | Add host to Observium
  command: "php {{ observium.install_dir }}/addhost.php {{ ansible_fqdn }} {{ snmp_comms.0 }} v2c && {{ observium.install_dir }}/poller-wrapper.py 16"
  args:
    chdir: "{{ observium.install_dir }}"
  delegate_to: "{{ groups.observium.0 }}"
  when: addhost.changed
  ignore_errors: true
