---
- name: Base | Check configuration
  assert:
    that:
      - "domains.lan is defined"
      - "resolvers is iterable"
      - "timezone is defined"
      - "lp.name is defined and lp.rev is defined"
    msg: Complete the basic configuration first

- include: system.yml
  tags: [ 'system' ]

- include: packages.yml
  tags: [ 'packages' ]

- include: time.yml
  tags: [ 'time' ]

- include: motd.yml
  tags: [ 'motd' ]

# Observium/LibreNMS Pluggable Monitoring Agent
- include: agent.yml
  tags: [ 'agent' ]

# RSyslog Daemon
- include: rsyslog.yml
  tags: [ 'syslog', 'rsyslog' ]

- include: zsh.yml
  tags: [ 'zsh' ]
