---
- name: Global | Configure APT-Cacher-NG Proxy
  template:
    src: apt/apt.conf.j2
    dest: /etc/apt/apt.conf.d/69apt-cacher-ng
  when: omit_apt_cache is not defined

- name: Debian | Remove Default sources.list
  file:
    path: /etc/apt/sources.list
    state: absent
  when: ansible_distribution == 'Debian'

- name: Global | apt preferences.d
  template:
    src: apt/pref.j2
    dest: "/etc/apt/preferences.d/{{ item.key }}.pref"
  with_dict: apt.prefs

- name: Debian | apt preferences.d (Debian-Security)
  template:
    src: apt/pref.j2
    dest: /etc/apt/preferences.d/security.pref
  when: ansible_distribution == 'Debian'

- name: Debian | apt sources.list (Debian-Security)
  template:
    src: apt/sources.list.j2
    dest: /etc/apt/sources.list.d/security.list
  with_dict: apt.security
  when: ansible_distribution == 'Debian'

- name: Global | apt sources.list
  template:
    src: apt/sources.list.j2
    dest: "/etc/apt/sources.list.d/{{ item.key }}.list"
  with_dict: apt.sources
  when: ansible_distribution == 'Debian'

- name: Global | apt sources.list (Contrib)
  template:
    src: apt/sources.list.j2
    dest: "/etc/apt/sources.list.d/{{ item.key }}.list"
  with_dict: apt.contrib

- name: Global | apt GPG Keys
  apt_key:
    url: "{{ item.url }}"
    validate_certs: no
  with_items: apt.gpg_keys | default([])

- name: Global | Basic Package Installation
  apt:
    name: "{{ item }}"
    cache_valid_time: "{{ apt.cachetime }}"
    update_cache: yes
  with_items:
    [ 'sudo', 'rsyslog', 'open-vm-tools',
      'iputils-arping', 'tcpdump', 'ethtool',
      'dnsutils', 'git', 'htop', 'hping3',
      'zsh', 'curl', 'ntpdate', 'mailutils',
      'python-mysqldb', 'ntp' ]
  tags: [ 'packages' ]
