---
- name: Global | Basic Package Installation
  apt:
    name: "{{ item }}"
    update_cache: yes
    cache_valid_time: "{{ apt_cache_valid | default('86400') }}"
  with_items:
    [ 'sudo', 'git', 'htop', 'zsh', 'curl', 'locales' ]
  tags: [ 'packages' ]

- name: Global | VMware-only packages
  apt:
    name: open-vm-tools
  when: ansible_virtualization_type == 'VMware'
  tags: [ 'packages' ]
