---
- name: Global | Configure APT-Cacher-NG Proxy
  template:
    src: apt/apt.conf.j2
    dest: /etc/apt/apt.conf.d/69apt-cacher-ng
  when: omit_apt_cache is not defined

- name: Global | Remove APT Proxy
  file:
    path: /etc/apt/apt.conf.d/69apt-cacher-ng
    state: absent
  when: omit_apt_cache is defined and omit_apt_cache

- name: Global | apt GPG Keys
  apt_key:
    url: "{{ item }}"
    validate_certs: yes
  with_items: "{{ apt_keys | default([]) }}"

- name: Debian | Remove Default sources.list
  file:
    path: /etc/apt/sources.list
    state: absent

- name: Global | apt preferences.d
  template:
    src: apt/pref.j2
    dest: "/etc/apt/preferences.d/{{ item.key }}.pref"
  with_dict: "{{ apt_sources }}"

- name: Global | apt sources.list.d/
  template:
    src: apt/sources.list.j2
    dest: "/etc/apt/sources.list.d/{{ item.key }}.list"
  with_dict: "{{ apt_sources }}"
  notify: update apt

- meta: flush_handlers

- name: Global | Basic Package Installation
  apt:
    name: "{{ item }}"
    update_cache: yes
    cache_valid_time: "{{ apt_cache_valid | default('86400') }}"
  with_items:
    [ 'sudo', 'git', 'htop', 'zsh', 'curl', 'locales' ]
  tags: [ 'packages' ]

- name: Global | VMware-only packages
  apt:
    name: open-vm-tools
  when: ansible_virtualization_type == 'VMware'
  tags: [ 'packages' ]
