---
- name: elastic | Install OpenJDK
  apt:
    name: openjdk-8-jre-headless
    default_release: testing
  tags: [ 'packages' ]

- name: elastic | Install elasticsearch
  apt:
    name: elasticsearch
  tags: [ 'packages' ]

- name: elastic | Set Heap Size
  lineinfile:
    line: "ES_HEAP_SIZE={{ (ansible_memtotal_mb | int * 0.75) | round | int }}m"
    regexp: '^\#?\s?ES_HEAP_SIZE'
    dest: /etc/default/elasticsearch
  notify: restart es

- name: elastic | Render Configuration
  template:
    src: es.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
  notify: restart es

- name: elastic | Start Service
  service:
    name: elasticsearch
    state: started
    enabled: true
