---
- name: Nginx | Render Site Template
  template:
    src: nginx.site.j2
    dest: /etc/nginx/sites-available/elasticsearch
  notify: reload nginx

- name: Nginx | Remove Default Site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: restart nginx

- name: Nginx | Symlink Site
  file:
    src: /etc/nginx/sites-available/elasticsearch
    dest: /etc/nginx/sites-enabled/elasticsearch
    state: link
  notify: reload nginx
