---
- name: IPTables | Ensure Config Directory
  file:
    path: /etc/iptables
    state: directory

- name: IPTables | Render Ruleset
  template:
    src: iptables.j2
    dest: "{{ iptables.path }}"
  notify: restore iptables

  # Don't use state=started, this only needs to run once on boot
- name: IPTables | Enable Service
  service:
    name=netfilter-persistent
    enabled=true
  tags: [ 'services' ]
