---
- name: Network | Render Interfaces
  template:
    src: netif.j2
    dest: /etc/network/interfaces
  notify: warn interfaces

- name: Netfilter | Install Package Suite
  apt:
    name: "{{ item }}"
    state: latest
    cache_valid_time: "{{ apt.cachetime }}"
    update_cache: yes
  with_items:
    [ 'iproute2', 'iptables', 'netfilter-persistent', 'iptables-persistent',
      'conntrack', 'conntrackd', 'netstat-nat', 'iptstate', 'ipset',
      'init-system-helpers', 'perl-base', 'ifupdown', 'snmpd' ]
  tags: [ 'packages' ]

- name: Kernel | IP Parameters
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    sysctl_set: yes
    state: present
    reload: yes
  with_items: kern.params
  tags: [ 'kernel' ]

- include: dhclient.yml
  tags: [ 'dhcp' ]

- include: tc.yml
  tags: [ 'tc' ]

- include: iptables.yml
  tags: [ 'iptables' ]
