---
- name: Deps | Install PHP / NodeJS
  apt:
    name: "{{ item }}"
    default_release: lanparty
  with_items:
    - php5-cli
    - php5-mysql
    - php5-json
    - php5-pthreads
    - nodejs
    - npm

- name: Deps | Install Composer
  get_url:
    url: https://getcomposer.org/composer.phar
    dest: /usr/local/bin/composer
    mode: 0755

- name: Deps | Enable pthreads Extension
  file:
    state: link
    src: /etc/php5/mods-available/pthreads.ini
    dest: /etc/php5/cli/conf.d/04-pthreads.ini
