---
- name: Install | eBot User
  user:
    name: ebot
    system: true

- name: Install | Add www-data to eBot group
  user:
    name: www-data
    groups: ebot
    system: true

- name: Install | Ensure Installation Directory
  file:
    state: directory
    path: "{{ ebot_install_dir }}"
    owner: ebot
    group: ebot

- name: Install | Git Checkout
  git:
    repo: https://github.com/ti-mo/eBot-CSGO.git
    version: threads
    dest: "{{ ebot_install_dir }}"
  become_user: ebot

- name: Install | Demo Folder Permissions
  file:
    path: "{{ ebot_install_dir }}/demos"
    owner: ebot
    group: ebot
    mode: 0755

- name: Install | Node Libraries
  npm:
    name: "{{ item }}"
    production: yes
    path: "{{ ebot_install_dir }}"
  with_items:
    - websocket
    - formidable
    - archiver

- name: Install | Compatible socket.io version
  npm:
    name: socket.io
    production: yes
    path: "{{ ebot_install_dir }}"
    version: 0.9.12

- name: Install | Composer Dependencies
  composer:
    working_dir: "{{ ebot_install_dir }}"
  tags: [ 'composer' ]

- name: Install | Systemd Unit File
  template:
    src: ebot.unit.j2
    dest: /lib/systemd/system/ebot.service
  notify: reload daemons

- name: Install | eBot Service
  service:
    name: ebot
    enabled: true
    state: started
