---
- name: Install isc-dhcp-server
  apt:
    name: isc-dhcp-server
  tags: [ 'packages' ]

- name: DHCPd Configuration
  template:
    src: dhcpd.j2
    dest: /etc/dhcp/dhcpd.conf
  notify: restart dhcpd
