---
- name: Configure | Render Environment
  template:
    src: consul.env.j2
    dest: /etc/default/consul
  notify: restart consul

- name: Configure | Render Configuration
  template:
    src: consul.config.j2
    dest: /etc/consul.d/config.json
  notify: restart consul
