---
- name: Install | Install Package
  apt:
    name: consul

- name: Install | Service Group
  group:
    name: consul
    system: true

- name: Install | Service User
  user:
    name: consul
    group: consul
    system: true
    createhome: false

- name: Install | consul.d Directory
  file:
    state: directory
    path: /etc/consul.d

- name: Install | /var/consul Directory
  file:
    state: directory
    path: /var/consul
    owner: consul
    group: consul

- name: Install | Render Unit File
  template:
    src: consul.unit.j2
    dest: /etc/systemd/system/consul.service
  notify: reload daemons

- name: Install | Render Nginx Site
  template:
    src: nginx.site.j2
    dest: /etc/nginx/sites-available/consul
  when: consul_inventory_group in group_names
  notify: reload nginx

- name: Install | Nginx Site Symlink
  file:
    state: link
    src: /etc/nginx/sites-available/consul
    dest: /etc/nginx/sites-enabled/consul
  when: consul_inventory_group in group_names

- meta: flush_handlers
