---
- name: Install | LogStash Packages
  apt:
    name: "{{ item }}"
  with_items:
    - logstash
    - logstash-contrib
  tags: [ 'packages' ]

- name: Install | Render Configurations
  template:
    src: "logstash/{{ item }}.j2"
    dest: "/etc/logstash/conf.d/{{ item }}.conf"
  notify: restart logstash
  with_items:
    - syslog
    - syslog_http

- name: Install | LogStash Service
  service:
    name: logstash
    state: started
    enabled: true
