---
- name: Install | OpenJDK
  apt:
    name: openjdk-8-jre-headless
    default_release: testing
  tags: [ 'packages' ]

- name: Install | LogStash
  apt:
    name: logstash
  tags: [ 'packages' ]

- name: Install | Render Configurations
  template:
    src: "logstash/{{ item }}.j2"
    dest: "/etc/logstash/conf.d/{{ item }}.conf"
  notify: restart logstash
  with_items:
    - syslog
    - filebeat

- name: Install | LogStash Service
  service:
    name: logstash
    state: started
    enabled: true
