---
- name: Install LogStash
  apt:
    name: "{{ item }}"
  with_items:
    - logstash
    - logstash-contrib
  tags: [ 'packages' ]

- name: Render LogStash Configurations
  template:
    src: "logstash/{{ item }}.j2"
    dest: "/etc/logstash/conf.d/{{ item }}.conf"
  notify: restart logstash
  with_items:
    - syslog

- name: LogStash Service
  service:
    name: logstash
    state: started
    enabled: true
