---
- name: Install | LogStash Packages
  apt:
    name: "{{ item }}"
  with_items:
    - logstash
  tags: [ 'packages' ]

- name: Install | Render Configurations
  template:
    src: "logstash/{{ item }}.j2"
    dest: "/etc/logstash/conf.d/{{ item }}.conf"
  notify: restart logstash
  with_items:
    - syslog
    - syslog_http

- name: Install | PKI Directory
  file:
    state: directory
    path: /etc/logstash/pki

- name: Install | LogStash Private Keys
  copy:
    dest: /etc/logstash/pki/{{ item }}
    src: files/keys/logstash/{{ item }}
  with_items:
    - logstash-forwarder.crt
    - logstash-forwarder.key

- name: Install | LogStash Service
  service:
    name: logstash
    state: started
    enabled: true
