---
- name: Main | Verify Credentials
  assert:
    that:
      - "lp.user is defined"
      - "lp.pass is defined"
    msg: Need credentials for ACNG admin panel at `lp.user` and `lp.pass`

- name: Main | Install Package
  apt:
    name: apt-cacher-ng
  tags: [ 'packages' ]

- name: Main | Render Configuration
  template:
    src: acng/acng.conf.j2
    dest: /etc/apt-cacher-ng/acng.conf
  notify: restart acng

- name: Main | Render Admin Credentials
  template:
    src: acng/security.conf.j2
    dest: /etc/apt-cacher-ng/security.conf
  notify: restart acng

- name: Main | Start Service
  service:
    name: apt-cacher-ng
    state: started
    enabled: true
  tags: [ 'services' ]
