---
- name: Apt Cache | Install Reprepro
  apt:
    name: reprepro
    cache_valid_time: "{{ apt.cachetime }}"
    update_cache: yes
  tags: [ 'packages' ]

- name: Apt Cache | Create Subdirs
  file:
    path: "{{ pkg.repo.path }}/{{ item }}"
    state: directory
    owner: www-data
    group: www-data
  with_items:
    - conf
    - incoming

- name: Apt Cache | Reprepro Distributions Configuration
  template:
    src: reprepro/conf.distributions.j2
    dest: "{{ pkg.repo.path }}/conf/distributions"

- name: Apt Cache | Reprepro Nginx Site
  template:
    src: reprepro/nginx.site.j2
    dest: /etc/nginx/sites-available/pkg
  notify: reload nginx
  tags: [ 'nginx' ]

- name: Apt Cache | Enable Reprepro Nginx Site
  file:
    src: /etc/nginx/sites-available/pkg
    dest: /etc/nginx/sites-enabled/pkg
    state: link
  notify: reload nginx
  tags: [ 'nginx' ]
