---
- name: Main | Smokeping Directory
  file:
    path: /etc/smokeping/config.d
    state: directory

# Render configs before the package installation
# Debian autostarts after install, which requires
# manual intervention to clean up the rrd's it generated
- name: Main | Render Smokeping Configs
  template:
    src: "{{ item }}.j2"
    dest: "/etc/smokeping/config.d/{{ item | title }}"
  with_items:
    - alerts
    - database
    - general
    - presentation
    - probes
    - slaves
    - targets
  notify: restart smokeping

- name: Main | Install Packages
  apt:
    name: "{{ item }}"
  with_items:
    - smokeping
    - sendmail
    - sendmail-bin
    - nginx
    - fcgiwrap
  tags: [ 'packages' ]

- name: Main | Smokeping Service
  service:
    name: smokeping
    state: started
    enabled: true
