---
# Make sure to always start netns-oob first,
# ssh-oob will not run without.
- include: util-linux.yml
  tags: [ 'util-linux' ]

- name: Out-of-Band Scripts
  template:
    src={{ item }}.init.j2
    dest=/etc/init.d/{{ item }}
    mode=0755
  with_items:
    - netns-oob
    - ssh-oob
  notify: restart ssh-oob

- name: Out-of-Band SSH Config
  template:
    src=sshd_oob.j2
    dest={{ oob.ssh.config_path }}
  notify: restart ssh-oob

- name: Nsenter Wrappers
  template:
    src=nsenter-oob.j2
    dest=/usr/bin/nsenter-{{ item.name }}
    mode=0755
  with_items: oob.nsenter

# Make sure to start netns-oob first
# TODO: unfuck this
- name: Out-of-Band Services
  service:
    name={{ item }}
    state=started
    enabled=false
  with_items:
    - netns-oob
    - ssh-oob
