---
# This forces installation of a more recent version of util-linux
# so we can finally use namespacing (nsenter etc.) properly.
# It forces an installation including all its dependencies from
# debian-testing, so remove this in the future.
- name: libc6
  apt:
    name=libc6=2.19-13
    default_release=testing
    update_cache=true
    cache_valid_time={{ apt.cachetime }}
  tags: [ 'packages' ]

# Util-linux pre-depends on libc6, so it cannot be installed atomically

- name: Util-Linux 2.25+
  apt:
    name={{ item }}
    default_release=testing
    state=latest
    update_cache=true
    cache_valid_time={{ apt.cachetime }}
  with_items:
    - util-linux
    - libblkid1
    - libmount1
    - libsmartcols1
  tags: [ 'packages' ]
